In [2]:

import numpy as np
list = [1, 2, 3, 4]
arr = np.array(list)
print("List  ", list)
print("Numpy Array  :",arr)


List   [1, 2, 3, 4]
Numpy Array  : [1 2 3 4]


In [3]:

import numpy as np
arr = np.array([3,4,5,6])
print("Array :",arr)


Array : [3 4 5 6]


In [4]:
import numpy as np
np.arange(1, 20 )


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [6]:
import numpy as np
np.linspace(2, 10, 5)


array([ 2.,  4.,  6.,  8., 10.])

In [7]:
import numpy as np
np.ones([4, 3])


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
import numpy as np
np.zeros([3, 3])


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print(a)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [13]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


In [15]:
import numpy as np 
a = np.arange(10) 
print(a[5:])

[5 6 7 8 9]


In [17]:
import numpy as np 
a = np.arange(10) 
print(a[4:7])

[4 5 6]


In [23]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print("array a\n")
print(a)  
print("\n")
print("array from index 0\n")
print(a[0:])
print("\n")
print("array from index 1\n")
print(a[1:])
print("\n")
print("array from index 2\n")
print(a[2:])


array a

[[1 2 3]
 [3 4 5]
 [4 5 6]]


array from index 0

[[1 2 3]
 [3 4 5]
 [4 5 6]]


array from index 1

[[3 4 5]
 [4 5 6]]


array from index 2

[[4 5 6]]


In [24]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


In [31]:
import numpy as np
a = np.arange(0,100,5)
a = a.reshape(4,5)

print("Original array is:")
print(a)
print ("\n")

print("Modified array is:")
for x in np.nditer(a):
   print(x),

print("\n")  
   
print("Transpose of the original array is:") 
b = a.T 
print(b) 

Original array is:
[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95


Transpose of the original array is:
[[ 0 25 50 75]
 [ 5 30 55 80]
 [10 35 60 85]
 [15 40 65 90]
 [20 45 70 95]]
